#bin/bash
#PBS -N test
#PBS be
#PBS -o ${HOME}/online_networks/code/o_files/output.log
#PBS -e ${HOME}/online_networks/code/e_files/error.log
#PBS -q parallel16
#PBS -t 1-5

cd ${HOME}/online_networks/code/simulation_studies/incomplete
export PYTHONPATH=${HOME}/online_networks/code/simulation_studies/incomplete

source ../../../online_networks_venv/bin/activate

python3 -u group_detection_sim_study.py > "progress_output/test_output_$PBS_ARRAYID.out"

