#bin/bash
#PBS -N test
#PBS be
#PBS -o ${HOME}/online_networks/code/simulation_studies/simulation_study_4/o_files/output.log
#PBS -e ${HOME}/online_networks/code/simulation_studies/simulation_study_4/e_files/error.log
#PBS -q parallel16
#PBS -t 0-29

cd ${HOME}/online_networks/code/simulation_studies/simulation_study_4

export PYTHONPATH=${HOME}/online_networks/code

source ../../../online_networks_venv/bin/activate

python3 -u simulation_study_4.py > "progress_output/test_output_$PBS_ARRAYID.out"

